// AUTO-GENERATED by scripts/build-iterations.mjs — do not edit by hand.
import type { Iteration } from "./types";

export const generatedRenders: Partial<Iteration>[] = [
  {
    "renderUrl": "/iterations/iter_001.png",
    "accuracy": 50.39,
    "originalPrompt": "Generate a GLSL shader reproducing the reference:\nGlowing fine white particle ribbons tracing a 3D strange attractor (Thomas/Lorenz-style do…",
    "refinedPrompt": "Initial shader (compiled); Procedural attractor ribbons with Gaussian falloff and simple bloom, animated by u_time.",
    "summary": "taste 50.4 · Initial shader (compiled); Procedural attractor ribbons with Gaussian falloff and simple bloom, animated by u_time."
  },
  {
    "renderUrl": "/iterations/iter_002.png",
    "accuracy": 54,
    "originalPrompt": "SIMILARITY: 1\nFIX (most important first):\n- **STRUCTURE:** The current geometry is a simple, soft capsule/blob, whereas the reference is a c",
    "refinedPrompt": "Improved (compiled); Replaced blob primitive with a torus‑knot ribbon parametric curve, added dense sampling for fine filaments, increased co",
    "summary": "taste 54.0 · Improved (compiled); Replaced blob primitive with a torus‑knot ribbon parametric curve, added dense sampling for fine filaments, increased co"
  },
  {
    "renderUrl": "/iterations/iter_003.png",
    "accuracy": 57.59,
    "originalPrompt": "SIMILARITY: 1\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is a flat, solid white shape with hard edges. The referen",
    "refinedPrompt": "Improved (compiled); Replaced torus‑knot geometry with a Thomas strange attractor, added many integration steps to create dense fine lines, a",
    "summary": "taste 57.6 · Improved (compiled); Replaced torus‑knot geometry with a Thomas strange attractor, added many integration steps to create dense fine lines, a"
  },
  {
    "renderUrl": "/iterations/iter_004.png",
    "accuracy": 58.25,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a single, thick, diagonal capsule/line segment.",
    "refinedPrompt": "Improved (compiled); Replaced thick line with a torus‑knot parametric curve, added fine‑Gaussian accumulation for filament look, applied stro",
    "summary": "taste 58.3 · Improved (compiled); Replaced thick line with a torus‑knot parametric curve, added fine‑Gaussian accumulation for filament look, applied stro"
  },
  {
    "renderUrl": "/iterations/iter_005.png",
    "accuracy": 59.91,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is stark, binary black-and-white with hard edges. The ref",
    "refinedPrompt": "Improved (compiled); Added additive‑compatible alpha output, increased sample count for finer ribbons, tightened curve, applied soft bloom to",
    "summary": "taste 59.9 · Improved (compiled); Added additive‑compatible alpha output, increased sample count for finer ribbons, tightened curve, applied soft bloom to"
  },
  {
    "renderUrl": "/iterations/iter_006.png",
    "accuracy": 63.86,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is harsh, solid white (#FFFFFF) with zero transparency. T",
    "refinedPrompt": "Improved (compiled); Added perspective projection, camera tilt, jitter noise for fine filament texture, reduced line width, and soft bloom wi",
    "summary": "taste 63.9 · Improved (compiled); Added perspective projection, camera tilt, jitter noise for fine filament texture, reduced line width, and soft bloom wi"
  },
  {
    "renderUrl": "/iterations/iter_007.png",
    "accuracy": 63.86,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **STRUCTURE (3D Depth vs. Flat Icon):** The current render is a flat, 2D symbol (a triquetra) v",
    "refinedPrompt": "No gain (0.4985 <= best 0.6386); reverted. Added perspective camera, thin core + separate halo for bloom, jitter for particle texture",
    "summary": "taste 63.9 · No gain (0.4985 <= best 0.6386); reverted. Added perspective camera, thin core + separate halo for bloom, jitter for particle texture"
  },
  {
    "renderUrl": "/iterations/iter_008.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is a flat, solid white shape with harsh edges. The refer",
    "refinedPrompt": "Improved (compiled); Added tube thickness, jittered fibers, flow animation, and exponential tone mapping to produce additive glowing ribbons",
    "summary": "taste 67.6 · Improved (compiled); Added tube thickness, jittered fibers, flow animation, and exponential tone mapping to produce additive glowing ribbons"
  },
  {
    "renderUrl": "/iterations/iter_009.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **DENSITY & VOLUME:** The current render is a sparse, single-pixel wireframe. The reference is a",
    "refinedPrompt": "No gain (0.6615 <= best 0.6760); reverted. Increased sample count and added three offset strands for volumetric density, thickened th",
    "summary": "taste 67.6 · No gain (0.6615 <= best 0.6760); reverted. Increased sample count and added three offset strands for volumetric density, thickened th"
  },
  {
    "renderUrl": "/iterations/iter_010.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is harsh, binary white-on-black. The reference is ethere",
    "refinedPrompt": "No gain (0.6482 <= best 0.6760); reverted. Added thicker, ring‑modulated tube, stronger soft fall‑off, higher step count, and a simpl",
    "summary": "taste 67.6 · No gain (0.6482 <= best 0.6760); reverted. Added thicker, ring‑modulated tube, stronger soft fall‑off, higher step count, and a simpl"
  },
  {
    "renderUrl": "/iterations/iter_011.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3/10\nFIX (most important first):\n- **COLOR/CONTRAST:** The reference image is high-energy and blazingly bright, whereas the curr",
    "refinedPrompt": "No gain (0.6400 <= best 0.6760); reverted. Increased radius for tube thickness, added outer glow, boosted exposure for bright additiv",
    "summary": "taste 67.6 · No gain (0.6400 <= best 0.6760); reverted. Increased radius for tube thickness, added outer glow, boosted exposure for bright additiv"
  },
  {
    "renderUrl": "/iterations/iter_012.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE (Geometry & Topology):** The current render is a **Trefoil knot** (3 lobes), but the",
    "refinedPrompt": "No gain (0.6100 <= best 0.6760); reverted. Switched to a figure‑eight knot, added a tube‑like core + halo, increased sample count, in",
    "summary": "taste 67.6 · No gain (0.6100 <= best 0.6760); reverted. Switched to a figure‑eight knot, added a tube‑like core + halo, increased sample count, in"
  },
  {
    "renderUrl": "/iterations/iter_013.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry Thickness):** The reference image depicts a volumetric, ribbon-like st",
    "refinedPrompt": "No gain (0.6532 <= best 0.6760); reverted. Added screen‑space tube thickness, a soft halo for bloom, softened colour, and denser samp",
    "summary": "taste 67.6 · No gain (0.6532 <= best 0.6760); reverted. Added screen‑space tube thickness, a soft halo for bloom, softened colour, and denser samp"
  },
  {
    "renderUrl": "/iterations/iter_014.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is stark, dim white pixels on black. The reference is a",
    "refinedPrompt": "No gain (0.6483 <= best 0.6760); reverted. Increased sampling steps and tube radius for a thick ribbon, added stronger exposure and g",
    "summary": "taste 67.6 · No gain (0.6483 <= best 0.6760); reverted. Increased sampling steps and tube radius for a thick ribbon, added stronger exposure and g"
  },
  {
    "renderUrl": "/iterations/iter_015.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is far too dim and low-contrast. The reference featur",
    "refinedPrompt": "No gain (0.6462 <= best 0.6760); reverted. Increased step count and radius for a thick, tube‑like ribbon; added a halo term for bloom",
    "summary": "taste 67.6 · No gain (0.6462 <= best 0.6760); reverted. Increased step count and radius for a thick, tube‑like ribbon; added a halo term for bloom"
  },
  {
    "renderUrl": "/iterations/iter_016.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3/10\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is a flat, binary white line on black. The reference i",
    "refinedPrompt": "No gain (0.6730 <= best 0.6760); reverted. Added thicker tube via larger core radius, introduced a halo radius for bloom, used radial",
    "summary": "taste 67.6 · No gain (0.6730 <= best 0.6760); reverted. Added thicker tube via larger core radius, introduced a halo radius for bloom, used radial"
  },
  {
    "renderUrl": "/iterations/iter_017.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **Add Bloom and Additive Blending (Color/Contrast):** The reference image features a luminou",
    "refinedPrompt": "No gain (0.6492 <= best 0.6760); reverted. Increased sample count and reduced step size for density, enlarged screen‑space radius for",
    "summary": "taste 67.6 · No gain (0.6492 <= best 0.6760); reverted. Increased sample count and reduced step size for density, enlarged screen‑space radius for"
  },
  {
    "renderUrl": "/iterations/iter_018.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is stark, hard-white pixels on black. The reference is a",
    "refinedPrompt": "No gain (0.6522 <= best 0.6760); reverted. Increased sample count and reduced step size for dense fibers, enlarged screen‑space radiu",
    "summary": "taste 67.6 · No gain (0.6522 <= best 0.6760); reverted. Increased sample count and reduced step size for dense fibers, enlarged screen‑space radiu"
  },
  {
    "renderUrl": "/iterations/iter_019.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is harsh, binary white-on-black with sharp edges. The",
    "refinedPrompt": "No gain (0.6550 <= best 0.6760); reverted. Increased sample count and added multiple offset strands to give the attractor a ribbon‑li",
    "summary": "taste 67.6 · No gain (0.6550 <= best 0.6760); reverted. Increased sample count and added multiple offset strands to give the attractor a ribbon‑li"
  },
  {
    "renderUrl": "/iterations/iter_020.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is far too dim and low-contrast. The reference featur",
    "refinedPrompt": "No gain (0.6342 <= best 0.6760); reverted. Increased exposure and added a simple bloom term, thickened the ribbon radius, raised step",
    "summary": "taste 67.6 · No gain (0.6342 <= best 0.6760); reverted. Increased exposure and added a simple bloom term, thickened the ribbon radius, raised step"
  },
  {
    "renderUrl": "/iterations/iter_021.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE (Geometry Thickness):** The current render is a thin, 1-pixel wireframe line. The re",
    "refinedPrompt": "No gain (0.6349 <= best 0.6760); reverted. Increased segment count and reduced step size for higher density; added a broader halo rad",
    "summary": "taste 67.6 · No gain (0.6349 <= best 0.6760); reverted. Increased segment count and reduced step size for higher density; added a broader halo rad"
  },
  {
    "renderUrl": "/iterations/iter_022.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 2/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a single, thin line (1D). The reference is a",
    "refinedPrompt": "No gain (0.4987 <= best 0.6760); reverted. Converted thin line to a true ribbon by using screen‑space perpendicular direction, added",
    "summary": "taste 67.6 · No gain (0.4987 <= best 0.6760); reverted. Converted thin line to a true ribbon by using screen‑space perpendicular direction, added"
  },
  {
    "renderUrl": "/iterations/iter_023.png",
    "accuracy": 67.6,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a single, thin 1D line. The reference is a volum",
    "refinedPrompt": "No gain (0.4723 <= best 0.6760); reverted. Converted the thin line into a screen‑space ribbon by using a perpendicular direction, inc",
    "summary": "taste 67.6 · No gain (0.4723 <= best 0.6760); reverted. Converted the thin line into a screen‑space ribbon by using a perpendicular direction, inc"
  },
  {
    "renderUrl": "/iterations/iter_024.png",
    "accuracy": 67.67,
    "originalPrompt": "SIMILARITY: 4/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is flat, stark white on black, lacking the luminous q",
    "refinedPrompt": "Improved (compiled); Added a soft halo for bloom, a procedural grid texture on the ribbon surface, increased visual thickness via halo radius",
    "summary": "taste 67.7 · Improved (compiled); Added a soft halo for bloom, a procedural grid texture on the ribbon surface, increased visual thickness via halo radius"
  },
  {
    "renderUrl": "/iterations/iter_025.png",
    "accuracy": 67.67,
    "originalPrompt": "SIMILARITY: 4/10\n\nFIX (most important first):\n- **STRUCTURE (3D Volume vs. 2D Line):** The current render is a flat, 2D loop. The reference",
    "refinedPrompt": "No gain (0.6315 <= best 0.6767); reverted. Implemented a true 3D tube by building a Frenet frame (normal/binormal) around the ribbon",
    "summary": "taste 67.7 · No gain (0.6315 <= best 0.6767); reverted. Implemented a true 3D tube by building a Frenet frame (normal/binormal) around the ribbon"
  },
  {
    "renderUrl": "/iterations/iter_026.png",
    "accuracy": 68.83,
    "originalPrompt": "SIMILARITY: 4/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry & Texture):** The current render is a flat, 2D-looking blurry line. Th",
    "refinedPrompt": "Improved (compiled); Implemented a thin ribbon mesh with cross‑hatch grid, added simple lighting based on ribbon normal, reduced core radius",
    "summary": "taste 68.8 · Improved (compiled); Implemented a thin ribbon mesh with cross‑hatch grid, added simple lighting based on ribbon normal, reduced core radius"
  },
  {
    "renderUrl": "/iterations/iter_027.png",
    "accuracy": 68.83,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a flat, thick line (or simple tube) lacking",
    "refinedPrompt": "No gain (0.6782 <= best 0.6883); reverted. Added tube geometry with longitudinal and angular grid lines, simple diffuse lighting for",
    "summary": "taste 68.8 · No gain (0.6782 <= best 0.6883); reverted. Added tube geometry with longitudinal and angular grid lines, simple diffuse lighting for"
  },
  {
    "renderUrl": "/iterations/iter_028.png",
    "accuracy": 72.81,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE (Ribbon vs. Line):** The current render is a single thick line (a 1D curve with",
    "refinedPrompt": "Improved (compiled); Converted the thick line into a true ribbon by offsetting along the binormal, added a screen‑space segment distance for",
    "summary": "taste 72.8 · Improved (compiled); Converted the thick line into a true ribbon by offsetting along the binormal, added a screen‑space segment distance for"
  },
  {
    "renderUrl": "/iterations/iter_029.png",
    "accuracy": 72.81,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **STRUCTURE:** The current render is a simple, single-curve loop. The reference is a complex, tw",
    "refinedPrompt": "No gain (0.6807 <= best 0.7281); reverted. Implemented a multi‑ribbon torus‑knot geometry, reduced core/halo radii for sharp 1‑px lin",
    "summary": "taste 72.8 · No gain (0.6807 <= best 0.7281); reverted. Implemented a multi‑ribbon torus‑knot geometry, reduced core/halo radii for sharp 1‑px lin"
  },
  {
    "renderUrl": "/iterations/iter_030.png",
    "accuracy": 72.81,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is fundamentally the wrong shape. The reference is",
    "refinedPrompt": "No gain (0.6907 <= best 0.7281); reverted. Implemented a closed‑loop torus‑knot ribbon with proper thickness, added a high‑frequency",
    "summary": "taste 72.8 · No gain (0.6907 <= best 0.7281); reverted. Implemented a closed‑loop torus‑knot ribbon with proper thickness, added a high‑frequency"
  },
  {
    "renderUrl": "/iterations/iter_031.png",
    "accuracy": 72.81,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The reference is a volumetric, twisted ribbon or tube (resembling",
    "refinedPrompt": "No gain (0.7035 <= best 0.7281); reverted. Added a thicker ribbon, wireframe‑like grid on both length and width, boosted lighting, st",
    "summary": "taste 72.8 · No gain (0.7035 <= best 0.7281); reverted. Added a thicker ribbon, wireframe‑like grid on both length and width, boosted lighting, st"
  },
  {
    "renderUrl": "/iterations/iter_032.png",
    "accuracy": 72.81,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally different. The reference depicts a volumetric, twis",
    "refinedPrompt": "No gain (0.6262 <= best 0.7281); reverted. Added circular cross‑section to form a 3D tube mesh, increased point density, boosted core",
    "summary": "taste 72.8 · No gain (0.6262 <= best 0.7281); reverted. Added circular cross‑section to form a 3D tube mesh, increased point density, boosted core"
  },
  {
    "renderUrl": "/iterations/iter_033.png",
    "accuracy": 73.62,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is far too dim and muddy. The reference is high-contr",
    "refinedPrompt": "Improved (compiled); Increased steps and reduced dt for higher density; tightened core/halo radii and added exponential tail fade for motion;",
    "summary": "taste 73.6 · Improved (compiled); Increased steps and reduced dt for higher density; tightened core/halo radii and added exponential tail fade for motion;"
  },
  {
    "renderUrl": "/iterations/iter_034.png",
    "accuracy": 73.62,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **STRUCTURE:** The reference depicts a volumetric, ribbon-like structure (a twisted torus or Mob",
    "refinedPrompt": "No gain (0.7251 <= best 0.7362); reverted. Added high‑density extrusion to create a ribbon, enlarged half‑width, increased halo radiu",
    "summary": "taste 73.6 · No gain (0.7251 <= best 0.7362); reverted. Added high‑density extrusion to create a ribbon, enlarged half‑width, increased halo radiu"
  },
  {
    "renderUrl": "/iterations/iter_035.png",
    "accuracy": 73.62,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **STRUCTURE (Ribbon Geometry):** The current render is a single-pixel-wide line of dots. The ref",
    "refinedPrompt": "No gain (0.6691 <= best 0.7362); reverted. Increased trail density, widened ribbon, added secondary halo for soft glow, reduced opaci",
    "summary": "taste 73.6 · No gain (0.6691 <= best 0.7362); reverted. Increased trail density, widened ribbon, added secondary halo for soft glow, reduced opaci"
  },
  {
    "renderUrl": "/iterations/iter_036.png",
    "accuracy": 74.36,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE (Line to Ribbon):** The reference image depicts a thick, volumetric ribbon or tube s",
    "refinedPrompt": "Improved (compiled); Increased step count and reduced dt for a denser ribbon; thickened halfWidth for visible tube; enlarged halo radius and",
    "summary": "taste 74.4 · Improved (compiled); Increased step count and reduced dt for a denser ribbon; thickened halfWidth for visible tube; enlarged halo radius and"
  },
  {
    "renderUrl": "/iterations/iter_037.png",
    "accuracy": 74.36,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is too soft, gray, and low-contrast. The reference fe",
    "refinedPrompt": "No gain (0.6687 <= best 0.7436); reverted. Made the ribbon ultra‑thin, boosted exposure for stark white lines, reduced halo size/weig",
    "summary": "taste 74.4 · No gain (0.6687 <= best 0.7436); reverted. Made the ribbon ultra‑thin, boosted exposure for stark white lines, reduced halo size/weig"
  },
  {
    "renderUrl": "/iterations/iter_038.png",
    "accuracy": 74.36,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a simple, thick, blurry loop (resembling a figu",
    "refinedPrompt": "No gain (0.7148 <= best 0.7436); reverted. Implemented a thin, twisted ribbon with self‑intersections, added a high‑frequency wirefra",
    "summary": "taste 74.4 · No gain (0.7148 <= best 0.7436); reverted. Implemented a thin, twisted ribbon with self‑intersections, added a high‑frequency wirefra"
  },
  {
    "renderUrl": "/iterations/iter_039.png",
    "accuracy": 74.36,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE (Geometry & Texture):** The current render is a smooth, blurry tube. The reference",
    "refinedPrompt": "No gain (0.6410 <= best 0.7436); reverted. Replaced thick ribbon with thin line segments, removed heavy halo blur, added strong addit",
    "summary": "taste 74.4 · No gain (0.6410 <= best 0.7436); reverted. Replaced thick ribbon with thin line segments, removed heavy halo blur, added strong addit"
  },
  {
    "renderUrl": "/iterations/iter_040.png",
    "accuracy": 74.36,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **DENSITY/TEXTURE (Critical):** The current render looks like a thick, blurry brush stroke o",
    "refinedPrompt": "No gain (0.6462 <= best 0.7436); reverted. Replaced thick ribbon tube with thousands of tiny particle points, reduced radii for sharp",
    "summary": "taste 74.4 · No gain (0.6462 <= best 0.7436); reverted. Replaced thick ribbon tube with thousands of tiny particle points, reduced radii for sharp"
  },
  {
    "renderUrl": "/iterations/iter_041.png",
    "accuracy": 74.36,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The reference depicts a complex, double-looping ribbon structure (",
    "refinedPrompt": "No gain (0.6625 <= best 0.7436); reverted. Created multiple parallel strands (wire‑frame mesh) from the attractor, tightened core/hal",
    "summary": "taste 74.4 · No gain (0.6625 <= best 0.7436); reverted. Created multiple parallel strands (wire‑frame mesh) from the attractor, tightened core/hal"
  },
  {
    "renderUrl": "/iterations/iter_042.png",
    "accuracy": 74.36,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **STRUCTURE:** The reference depicts a complex, volumetric **ribbon or tube** with internal geom",
    "refinedPrompt": "No gain (0.6607 <= best 0.7436); reverted. Converted thick flat line to a thin 3D ribbon with a crisp core and minimal halo. Added a",
    "summary": "taste 74.4 · No gain (0.6607 <= best 0.7436); reverted. Converted thick flat line to a thin 3D ribbon with a crisp core and minimal halo. Added a"
  },
  {
    "renderUrl": "/iterations/iter_043.png",
    "accuracy": 74.36,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The current render is a simple, thin tube or line. The reference is a wide, twis",
    "refinedPrompt": "No gain (0.7227 <= best 0.7436); reverted. Widened ribbon into a true strip, added fine grid texture, bright hot core with radial fal",
    "summary": "taste 74.4 · No gain (0.7227 <= best 0.7436); reverted. Widened ribbon into a true strip, added fine grid texture, bright hot core with radial fal"
  },
  {
    "renderUrl": "/iterations/iter_044.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a simple, thick line or tube. The reference is a",
    "refinedPrompt": "Improved (compiled); Widened ribbon to a true ribbon, added high‑frequency jitter for fibrous texture, reduced core/halo radii and halo weigh",
    "summary": "taste 75.2 · Improved (compiled); Widened ribbon to a true ribbon, added high‑frequency jitter for fibrous texture, reduced core/halo radii and halo weigh"
  },
  {
    "renderUrl": "/iterations/iter_045.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. Image 2 depicts simple, thick intersect",
    "refinedPrompt": "Candidate render was flat (std<0.02); reverted to best.",
    "summary": "taste 75.2 · Candidate render was flat (std<0.02); reverted to best."
  },
  {
    "renderUrl": "/iterations/iter_046.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render depicts simple, thick intersecting rings (like a V",
    "refinedPrompt": "No gain (0.5369 <= best 0.7520); reverted. Replaced thick ring geometry with a fine chaotic attractor ribbon, reduced line width, inc",
    "summary": "taste 75.2 · No gain (0.5369 <= best 0.7520); reverted. Replaced thick ring geometry with a fine chaotic attractor ribbon, reduced line width, inc"
  },
  {
    "renderUrl": "/iterations/iter_047.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference image displays a complex,",
    "refinedPrompt": "Candidate render was flat (std<0.02); reverted to best.",
    "summary": "taste 75.2 · Candidate render was flat (std<0.02); reverted to best."
  },
  {
    "renderUrl": "/iterations/iter_048.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is too dim and grey. The reference features brilliant, h",
    "refinedPrompt": "No gain (0.5397 <= best 0.7520); reverted. Increased contrast and brightness, switched to a more chaotic attractor curve, reduced rib",
    "summary": "taste 75.2 · No gain (0.5397 <= best 0.7520); reverted. Increased contrast and brightness, switched to a more chaotic attractor curve, reduced rib"
  },
  {
    "renderUrl": "/iterations/iter_049.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference depicts a complex, twi",
    "refinedPrompt": "No gain (0.6333 <= best 0.7520); reverted. Replaced simple torus geometry with a twisted attractor ribbon, increased sampling density",
    "summary": "taste 75.2 · No gain (0.6333 <= best 0.7520); reverted. Replaced simple torus geometry with a twisted attractor ribbon, increased sampling density"
  },
  {
    "renderUrl": "/iterations/iter_050.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference depicts a complex, twiste",
    "refinedPrompt": "No gain (0.6482 <= best 0.7520); reverted. Replaced simple torus geometry with a 2‑3 torus‑knot giving a twisted ribbon shape. Reduce",
    "summary": "taste 75.2 · No gain (0.6482 <= best 0.7520); reverted. Replaced simple torus geometry with a 2‑3 torus‑knot giving a twisted ribbon shape. Reduce"
  },
  {
    "renderUrl": "/iterations/iter_051.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is far too dim and gray. The reference features brillian",
    "refinedPrompt": "No gain (0.6767 <= best 0.7520); reverted. Thinned ribbon to 0.006 width, increased density, removed jitter, added stronger bloom via",
    "summary": "taste 75.2 · No gain (0.6767 <= best 0.7520); reverted. Thinned ribbon to 0.006 width, increased density, removed jitter, added stronger bloom via"
  },
  {
    "renderUrl": "/iterations/iter_052.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference displays a complex, twiste",
    "refinedPrompt": "No gain (0.6512 <= best 0.7520); reverted. Replaced thick ribbon extrusion with a thin line sampled from a parametric attractor, adde",
    "summary": "taste 75.2 · No gain (0.6512 <= best 0.7520); reverted. Replaced thick ribbon extrusion with a thin line sampled from a parametric attractor, adde"
  },
  {
    "renderUrl": "/iterations/iter_053.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current geometry is too simple. The reference image depicts a com",
    "refinedPrompt": "Candidate render was flat (std<0.02); reverted to best.",
    "summary": "taste 75.2 · Candidate render was flat (std<0.02); reverted to best."
  },
  {
    "renderUrl": "/iterations/iter_054.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current geometry is fundamentally different. The reference dep",
    "refinedPrompt": "No gain (0.5828 <= best 0.7520); reverted. Replaced simple sinusoidal ribbon with a Lorenz attractor integration for a true twisted r",
    "summary": "taste 75.2 · No gain (0.5828 <= best 0.7520); reverted. Replaced simple sinusoidal ribbon with a Lorenz attractor integration for a true twisted r"
  },
  {
    "renderUrl": "/iterations/iter_055.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is too dim and grey. The reference features brilliant, h",
    "refinedPrompt": "No gain (0.5916 <= best 0.7520); reverted. Increased emission (exposure 12), thinned ribbon (halfWidth 0.008), added soft halo, raise",
    "summary": "taste 75.2 · No gain (0.5916 <= best 0.7520); reverted. Increased emission (exposure 12), thinned ribbon (halfWidth 0.008), added soft halo, raise"
  },
  {
    "renderUrl": "/iterations/iter_056.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is too dark and flat grey. The reference is a brilliant,",
    "refinedPrompt": "No gain (0.6895 <= best 0.7520); reverted. Made ribbons ultra‑thin (halfWidth 0.004) and boosted halo weight for bloom. Increased ste",
    "summary": "taste 75.2 · No gain (0.6895 <= best 0.7520); reverted. Made ribbons ultra‑thin (halfWidth 0.004) and boosted halo weight for bloom. Increased ste"
  },
  {
    "renderUrl": "/iterations/iter_057.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **STRUCTURE:** The underlying geometry is fundamentally different. The reference depicts a compl",
    "refinedPrompt": "No gain (0.5765 <= best 0.7520); reverted. Replaced uniform torus‑knot path with a Thomas chaotic attractor, thinned ribbon width, ad",
    "summary": "taste 75.2 · No gain (0.5765 <= best 0.7520); reverted. Replaced uniform torus‑knot path with a Thomas chaotic attractor, thinned ribbon width, ad"
  },
  {
    "renderUrl": "/iterations/iter_058.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **GLOW & BLOOM:** The reference image depicts light trails or energy, requiring a strong \"bl",
    "refinedPrompt": "No gain (0.5455 <= best 0.7520); reverted. Added a larger halo and an extra bloom term for soft glow, reduced ribbon half‑width for h",
    "summary": "taste 75.2 · No gain (0.5455 <= best 0.7520); reverted. Added a larger halo and an extra bloom term for soft glow, reduced ribbon half‑width for h"
  },
  {
    "renderUrl": "/iterations/iter_059.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **DENSITY/TEXTURE:** The current render looks like a coarse, grainy tube. The reference is comp",
    "refinedPrompt": "No gain (0.6482 <= best 0.7520); reverted. Increased particle density (12000 steps) and reduced strand width for fine hair‑like look.",
    "summary": "taste 75.2 · No gain (0.6482 <= best 0.7520); reverted. Increased particle density (12000 steps) and reduced strand width for fine hair‑like look."
  },
  {
    "renderUrl": "/iterations/iter_060.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally wrong. The reference depicts a complex, twisted ri",
    "refinedPrompt": "No gain (0.6413 <= best 0.7520); reverted. Replaced simple torus loop with a twisted figure‑8 attractor, increased particle steps to",
    "summary": "taste 75.2 · No gain (0.6413 <= best 0.7520); reverted. Replaced simple torus loop with a twisted figure‑8 attractor, increased particle steps to"
  },
  {
    "renderUrl": "/iterations/iter_061.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally different. The reference depicts a complex, twiste",
    "refinedPrompt": "No gain (0.5163 <= best 0.7520); reverted. Made ribbon taller and more twisted, thinned the filament, increased step count, added str",
    "summary": "taste 75.2 · No gain (0.5163 <= best 0.7520); reverted. Made ribbon taller and more twisted, thinned the filament, increased step count, added str"
  },
  {
    "renderUrl": "/iterations/iter_062.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The reference image features a high-contrast, luminous aesthetic where the",
    "refinedPrompt": "No gain (0.6766 <= best 0.7520); reverted. Replaced simple ring with a (2,3) torus knot for self‑intersecting geometry, thinned the r",
    "summary": "taste 75.2 · No gain (0.6766 <= best 0.7520); reverted. Replaced simple ring with a (2,3) torus knot for self‑intersecting geometry, thinned the r"
  },
  {
    "renderUrl": "/iterations/iter_063.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference displays a classic double",
    "refinedPrompt": "No gain (0.5584 <= best 0.7520); reverted. Replaced single‑loop ribbon with a double‑lobed analytic attractor, thinned geometry, incr",
    "summary": "taste 75.2 · No gain (0.5584 <= best 0.7520); reverted. Replaced single‑loop ribbon with a double‑lobed analytic attractor, thinned geometry, incr"
  },
  {
    "renderUrl": "/iterations/iter_064.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a thick, solid-looking tube, whereas the refere",
    "refinedPrompt": "No gain (0.5562 <= best 0.7520); reverted. Thinned geometry to wire‑like lines, added a second phase‑shifted strand for double‑lobed",
    "summary": "taste 75.2 · No gain (0.5562 <= best 0.7520); reverted. Thinned geometry to wire‑like lines, added a second phase‑shifted strand for double‑lobed"
  },
  {
    "renderUrl": "/iterations/iter_065.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render uses thick, uniform tubes (likely a torus knot), w",
    "refinedPrompt": "No gain (0.7163 <= best 0.7520); reverted. Made ribbons thin (baseHalfWidth 0.004) with sinusoidal width modulation, increased step c",
    "summary": "taste 75.2 · No gain (0.7163 <= best 0.7520); reverted. Made ribbons thin (baseHalfWidth 0.004) with sinusoidal width modulation, increased step c"
  },
  {
    "renderUrl": "/iterations/iter_066.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference depicts a **Lorenz Attrac",
    "refinedPrompt": "No gain (0.6055 <= best 0.7520); reverted. Replaced the previous torus‑knot geometry with a true Lorenz attractor using an explicit E",
    "summary": "taste 75.2 · No gain (0.6055 <= best 0.7520); reverted. Replaced the previous torus‑knot geometry with a true Lorenz attractor using an explicit E"
  },
  {
    "renderUrl": "/iterations/iter_067.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference shows a complex, double-l",
    "refinedPrompt": "Candidate render was flat (std<0.02); reverted to best.",
    "summary": "taste 75.2 · Candidate render was flat (std<0.02); reverted to best."
  },
  {
    "renderUrl": "/iterations/iter_068.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is far too dark and grey. The reference is high-contr",
    "refinedPrompt": "No gain (0.7158 <= best 0.7520); reverted. Made ribbon thin, added twist, increased steps for density, boosted exposure and halo weig",
    "summary": "taste 75.2 · No gain (0.7158 <= best 0.7520); reverted. Made ribbon thin, added twist, increased steps for density, boosted exposure and halo weig"
  },
  {
    "renderUrl": "/iterations/iter_069.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render uses thick, tube-like rings that simply intersect.",
    "refinedPrompt": "No gain (0.6991 <= best 0.7520); reverted. Replaced thick torus geometry with a thin twisted ribbon using a rotating binormal, added",
    "summary": "taste 75.2 · No gain (0.6991 <= best 0.7520); reverted. Replaced thick torus geometry with a thin twisted ribbon using a rotating binormal, added"
  },
  {
    "renderUrl": "/iterations/iter_070.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is incorrect. The reference image displays the classic double-lo",
    "refinedPrompt": "No gain (0.5923 <= best 0.7520); reverted. Replaced the single‑loop parametric ribbon with a Lorenz attractor integration (double‑lob",
    "summary": "taste 75.2 · No gain (0.5923 <= best 0.7520); reverted. Replaced the single‑loop parametric ribbon with a Lorenz attractor integration (double‑lob"
  },
  {
    "renderUrl": "/iterations/iter_071.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally different. The reference is a complex, twisted rib",
    "refinedPrompt": "No gain (0.5601 <= best 0.7520); reverted. Replaced simple loop with a torus‑knot attractor for richer twisting, reduced filament hal",
    "summary": "taste 75.2 · No gain (0.5601 <= best 0.7520); reverted. Replaced simple loop with a torus‑knot attractor for richer twisting, reduced filament hal"
  },
  {
    "renderUrl": "/iterations/iter_072.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current geometry is fundamentally wrong. You are rendering simple",
    "refinedPrompt": "No gain (0.5962 <= best 0.7520); reverted. Replaced the original ring geometry with a Lorenz attractor integration to produce the dou",
    "summary": "taste 75.2 · No gain (0.5962 <= best 0.7520); reverted. Replaced the original ring geometry with a Lorenz attractor integration to produce the dou"
  },
  {
    "renderUrl": "/iterations/iter_073.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **DENSITY & RENDERING STYLE:** The current render looks like a thick, opaque, noisy tube or rib",
    "refinedPrompt": "No gain (0.6601 <= best 0.7520); reverted. Reduced ribbon thickness, sharpened core, stronger halo, higher exposure for additive brig",
    "summary": "taste 75.2 · No gain (0.6601 <= best 0.7520); reverted. Reduced ribbon thickness, sharpened core, stronger halo, higher exposure for additive brig"
  },
  {
    "renderUrl": "/iterations/iter_074.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 4\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is too dim and grey. The reference is high-contrast with",
    "refinedPrompt": "No gain (0.7308 <= best 0.7520); reverted. Made ribbon much thinner, increased exposure for near‑white highlights, flattened the attr",
    "summary": "taste 75.2 · No gain (0.7308 <= best 0.7520); reverted. Made ribbon much thinner, increased exposure for near‑white highlights, flattened the attr"
  },
  {
    "renderUrl": "/iterations/iter_075.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference displays a complex, multi",
    "refinedPrompt": "No gain (0.5764 <= best 0.7520); reverted. Replaced flat figure‑8 geometry with a Thomas‑style attractor, thinned ribbon width, added",
    "summary": "taste 75.2 · No gain (0.5764 <= best 0.7520); reverted. Replaced flat figure‑8 geometry with a Thomas‑style attractor, thinned ribbon width, added"
  },
  {
    "renderUrl": "/iterations/iter_076.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally different. The reference is a wide, twisting ri",
    "refinedPrompt": "No gain (0.7242 <= best 0.7520); reverted. Refined geometry to a thin planar ribbon (halfWidth reduced), increased step count for fin",
    "summary": "taste 75.2 · No gain (0.7242 <= best 0.7520); reverted. Refined geometry to a thin planar ribbon (halfWidth reduced), increased step count for fin"
  },
  {
    "renderUrl": "/iterations/iter_077.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally wrong. The reference depicts a complex, multi-l",
    "refinedPrompt": "No gain (0.5152 <= best 0.7520); reverted. Replaced simple torus ribbon with a Thomas chaotic attractor, reduced ribbon half‑width to",
    "summary": "taste 75.2 · No gain (0.5152 <= best 0.7520); reverted. Replaced simple torus ribbon with a Thomas chaotic attractor, reduced ribbon half‑width to"
  },
  {
    "renderUrl": "/iterations/iter_078.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **STRUCTURE (Geometry Type):** The underlying shape is incorrect. The reference is a **Lorenz A",
    "refinedPrompt": "No gain (0.6260 <= best 0.7520); reverted. Replaced the placeholder loop with a Lorenz attractor integration, flattened the ribbon to",
    "summary": "taste 75.2 · No gain (0.6260 <= best 0.7520); reverted. Replaced the placeholder loop with a Lorenz attractor integration, flattened the ribbon to"
  },
  {
    "renderUrl": "/iterations/iter_079.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The fundamental shape is incorrect. The reference is a **Lorenz Attra",
    "refinedPrompt": "No gain (0.6098 <= best 0.7520); reverted. Replaced custom ribbon with a Lorenz attractor integration, reduced strand thickness, adde",
    "summary": "taste 75.2 · No gain (0.6098 <= best 0.7520); reverted. Replaced custom ribbon with a Lorenz attractor integration, reduced strand thickness, adde"
  },
  {
    "renderUrl": "/iterations/iter_080.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry Mismatch):** The current render (Image 2) displays a thick, simple int",
    "refinedPrompt": "No gain (0.6339 <= best 0.7520); reverted. Replaced torus‑knot geometry with a Lorenz attractor integration, thinned the ribbon to ~1",
    "summary": "taste 75.2 · No gain (0.6339 <= best 0.7520); reverted. Replaced torus‑knot geometry with a Lorenz attractor integration, thinned the ribbon to ~1"
  },
  {
    "renderUrl": "/iterations/iter_081.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference depicts a complex \"strange",
    "refinedPrompt": "No gain (0.6196 <= best 0.7520); reverted. Replaced the simple ribbon equation with a Thomas chaotic attractor integrated per‑step, t",
    "summary": "taste 75.2 · No gain (0.6196 <= best 0.7520); reverted. Replaced the simple ribbon equation with a Thomas chaotic attractor integrated per‑step, t"
  },
  {
    "renderUrl": "/iterations/iter_082.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is completely different. You have rendered two simple, thick int",
    "refinedPrompt": "No gain (0.6607 <= best 0.7520); reverted. Replaced thick ribbon extrusion with a high‑density line‑segment rendering of a chaotic at",
    "summary": "taste 75.2 · No gain (0.6607 <= best 0.7520); reverted. Replaced thick ribbon extrusion with a high‑density line‑segment rendering of a chaotic at"
  },
  {
    "renderUrl": "/iterations/iter_083.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE:** The current geometry is fundamentally wrong. You are rendering simple intersectin",
    "refinedPrompt": "No gain (0.5976 <= best 0.7520); reverted. Replaced ring geometry with a Thomas attractor integration, thinned line width, added stro",
    "summary": "taste 75.2 · No gain (0.5976 <= best 0.7520); reverted. Replaced ring geometry with a Thomas attractor integration, thinned line width, added stro"
  },
  {
    "renderUrl": "/iterations/iter_084.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference image depicts a complex,",
    "refinedPrompt": "No gain (0.5731 <= best 0.7520); reverted. Replaced uniform ring geometry with a thin, chaotic attractor ribbon, increased step count",
    "summary": "taste 75.2 · No gain (0.5731 <= best 0.7520); reverted. Replaced uniform ring geometry with a thin, chaotic attractor ribbon, increased step count"
  },
  {
    "renderUrl": "/iterations/iter_085.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference depicts a complex, multi-",
    "refinedPrompt": "No gain (0.5614 <= best 0.7520); reverted. Replaced simple torus knot with Lorenz attractor integration, thinned ribbon, added warm‑t",
    "summary": "taste 75.2 · No gain (0.5614 <= best 0.7520); reverted. Replaced simple torus knot with Lorenz attractor integration, thinned ribbon, added warm‑t"
  },
  {
    "renderUrl": "/iterations/iter_086.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **DENSITY/TEXTURE (Critical):** The current render looks like thick, noisy tubes. The refere",
    "refinedPrompt": "No gain (0.5389 <= best 0.7520); reverted. Increased step count to 12000, thinned ribbon to 0.008, enlarged halo for bloom, raised ex",
    "summary": "taste 75.2 · No gain (0.5389 <= best 0.7520); reverted. Increased step count to 12000, thinned ribbon to 0.008, enlarged halo for bloom, raised ex"
  },
  {
    "renderUrl": "/iterations/iter_087.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a thick, simple knot (resembling a trefoil), whe",
    "refinedPrompt": "Candidate render was flat (std<0.02); reverted to best.",
    "summary": "taste 75.2 · Candidate render was flat (std<0.02); reverted to best."
  },
  {
    "renderUrl": "/iterations/iter_088.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally different. The reference displays a complex, twist",
    "refinedPrompt": "No gain (0.6446 <= best 0.7520); reverted. Replaced simple torus‑like parametric curve with a double‑lobed sinusoidal ribbon, thinned",
    "summary": "taste 75.2 · No gain (0.6446 <= best 0.7520); reverted. Replaced simple torus‑like parametric curve with a double‑lobed sinusoidal ribbon, thinned"
  },
  {
    "renderUrl": "/iterations/iter_089.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference depicts a complex, twi",
    "refinedPrompt": "No gain (0.6043 <= best 0.7520); reverted. Replaced simple rings with a parametric double‑lobe attractor, thinned ribbon width, incre",
    "summary": "taste 75.2 · No gain (0.6043 <= best 0.7520); reverted. Replaced simple rings with a parametric double‑lobe attractor, thinned ribbon width, incre"
  },
  {
    "renderUrl": "/iterations/iter_090.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is fundamentally the wrong shape. The reference",
    "refinedPrompt": "No gain (0.6528 <= best 0.7520); reverted. Replaced the old torus‑knot formula with a butterfly‑curve based double‑lobe attractor, re",
    "summary": "taste 75.2 · No gain (0.6528 <= best 0.7520); reverted. Replaced the old torus‑knot formula with a butterfly‑curve based double‑lobe attractor, re"
  },
  {
    "renderUrl": "/iterations/iter_091.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current shape is a simple, symmetric intersecting ring (likely a",
    "refinedPrompt": "No gain (0.6026 <= best 0.7520); reverted. Replaced torus‑knot geometry with a Lorenz attractor integration, thinned the ribbon, incr",
    "summary": "taste 75.2 · No gain (0.6026 <= best 0.7520); reverted. Replaced torus‑knot geometry with a Lorenz attractor integration, thinned the ribbon, incr"
  },
  {
    "renderUrl": "/iterations/iter_092.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally different. The reference depicts a complex, contin",
    "refinedPrompt": "No gain (0.6222 <= best 0.7520); reverted. Replaced simple ring geometry with a multi‑frequency folded attractor curve, thinned ribbo",
    "summary": "taste 75.2 · No gain (0.6222 <= best 0.7520); reverted. Replaced simple ring geometry with a multi‑frequency folded attractor curve, thinned ribbo"
  },
  {
    "renderUrl": "/iterations/iter_093.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally different. The reference is a complex, twisted rib",
    "refinedPrompt": "No gain (0.6281 <= best 0.7520); reverted. Replaced torus geometry with a thin, twisting attractor ribbon; removed grid texture and j",
    "summary": "taste 75.2 · No gain (0.6281 <= best 0.7520); reverted. Replaced torus geometry with a thin, twisting attractor ribbon; removed grid texture and j"
  },
  {
    "renderUrl": "/iterations/iter_094.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference depicts a thin, twisting",
    "refinedPrompt": "No gain (0.6213 <= best 0.7520); reverted. Narrowed ribbon to a thin strip, refined parametric curve for double‑lobe shape, boosted e",
    "summary": "taste 75.2 · No gain (0.6213 <= best 0.7520); reverted. Narrowed ribbon to a thin strip, refined parametric curve for double‑lobe shape, boosted e"
  },
  {
    "renderUrl": "/iterations/iter_095.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is too dark and grey. The reference is high-contrast,",
    "refinedPrompt": "No gain (0.5798 <= best 0.7520); reverted. Made ribbon much thinner, increased density, brightened via higher exposure and stronger h",
    "summary": "taste 75.2 · No gain (0.5798 <= best 0.7520); reverted. Made ribbon much thinner, increased density, brightened via higher exposure and stronger h"
  },
  {
    "renderUrl": "/iterations/iter_096.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **STRUCTURE (Geometry):** The current render is a simple, thick loop (resembling a torus or",
    "refinedPrompt": "No gain (0.6160 <= best 0.7520); reverted. Replaced the original loop shape with a Lorenz attractor (Euler integration) to create the",
    "summary": "taste 75.2 · No gain (0.6160 <= best 0.7520); reverted. Replaced the original loop shape with a Lorenz attractor (Euler integration) to create the"
  },
  {
    "renderUrl": "/iterations/iter_097.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is too grey and flat. The reference is a brilliant, high-",
    "refinedPrompt": "No gain (0.6995 <= best 0.7520); reverted. Increased emission via higher exposure and uniform lighting, switched to a thin hair‑width",
    "summary": "taste 75.2 · No gain (0.6995 <= best 0.7520); reverted. Increased emission via higher exposure and uniform lighting, switched to a thin hair‑width"
  },
  {
    "renderUrl": "/iterations/iter_098.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 2\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference shows a complex, continuou",
    "refinedPrompt": "No gain (0.5799 <= best 0.7520); reverted. Replaced simple loop geometry with a Thomas attractor integration to produce a twisted, vo",
    "summary": "taste 75.2 · No gain (0.5799 <= best 0.7520); reverted. Replaced simple loop geometry with a Thomas attractor integration to produce a twisted, vo"
  },
  {
    "renderUrl": "/iterations/iter_099.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3/10\n\nFIX (most important first):\n- **COLOR/CONTRAST:** The current render is stark, solid white with hard edges. The reference",
    "refinedPrompt": "No gain (0.5468 <= best 0.7520); reverted. Reduced ribbon thickness, added a larger soft halo for bloom, increased step count for fin",
    "summary": "taste 75.2 · No gain (0.5468 <= best 0.7520); reverted. Reduced ribbon thickness, added a larger soft halo for bloom, increased step count for fin"
  },
  {
    "renderUrl": "/iterations/iter_100.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference displays a complex, twist",
    "refinedPrompt": "No gain (0.6691 <= best 0.7520); reverted. Replaced simple ring geometry with a (2,3) torus‑knot for true twisted 3D ribbons, thinned",
    "summary": "taste 75.2 · No gain (0.6691 <= best 0.7520); reverted. Replaced simple ring geometry with a (2,3) torus‑knot for true twisted 3D ribbons, thinned"
  },
  {
    "renderUrl": "/iterations/iter_101.png",
    "accuracy": 75.2,
    "originalPrompt": "SIMILARITY: 3\n\nFIX (most important first):\n- **STRUCTURE:** The geometry is fundamentally incorrect. The reference depicts a complex, contin",
    "refinedPrompt": "No gain (0.6780 <= best 0.7520); reverted. Replaced simple torus geometry with a twisted double‑lobe curve, thinned ribbon edges, inc",
    "summary": "taste 75.2 · No gain (0.6780 <= best 0.7520); reverted. Replaced simple torus geometry with a twisted double‑lobe curve, thinned ribbon edges, inc"
  }
];

export const generatedMeta = {
  "runId": 9,
  "count": 101,
  "bestAccuracy": 75.2
} as const;
